#pragma once
#include <GLFW/glfw3.h>
enum KeyKode
{
    /* Letter keys */
    A = GLFW_KEY_A,
    B = GLFW_KEY_B,
    C = GLFW_KEY_C,
    D = GLFW_KEY_D,
    E = GLFW_KEY_E,
    F = GLFW_KEY_F,
    G = GLFW_KEY_G,
    H = GLFW_KEY_H,
    I = GLFW_KEY_I,
    J = GLFW_KEY_J,
    K = GLFW_KEY_K,
    L = GLFW_KEY_L,
    M = GLFW_KEY_M,
    N = GLFW_KEY_N,
    O = GLFW_KEY_O,
    P = GLFW_KEY_P,
    Q = GLFW_KEY_Q,
    R = GLFW_KEY_R,
    S = GLFW_KEY_S,
    T = GLFW_KEY_T,
    U = GLFW_KEY_U,
    V = GLFW_KEY_V,
    SW = GLFW_KEY_W,
    X = GLFW_KEY_X,
    Y = GLFW_KEY_Y,
    Z = GLFW_KEY_Z,
    /* Number keys */
    NUM0 = GLFW_KEY_0,
    NUM1 = GLFW_KEY_1,
    NUM2 = GLFW_KEY_2,
    NUM3 = GLFW_KEY_3,
    NUM4 = GLFW_KEY_4,
    NUM5 = GLFW_KEY_5,
    NUM6 = GLFW_KEY_6,
    NUM7 = GLFW_KEY_7,
    NUM8 = GLFW_KEY_8,
    NUM9 = GLFW_KEY_9,
    NUMPAD_0 = GLFW_KEY_KP_0,
    NUMPAD_1 = GLFW_KEY_KP_1,
    NUMPAD_2 = GLFW_KEY_KP_2,
    NUMPAD_3 = GLFW_KEY_KP_3,
    NUMPAD_4 = GLFW_KEY_KP_4,
    NUMPAD_5 = GLFW_KEY_KP_5,
    NUMPAD_6 = GLFW_KEY_KP_6,
    NUMPAD_7 = GLFW_KEY_KP_7,
    NUMPAD_8 = GLFW_KEY_KP_8,
    NUMPAD_9 = GLFW_KEY_KP_9,
    /* Function keys */
    ESCAPE = GLFW_KEY_ESCAPE,
    ENTER = GLFW_KEY_ENTER,
    END = GLFW_KEY_END,
    TAB = GLFW_KEY_TAB,
    BACKSPACE = GLFW_KEY_BACKSPACE,
    DELETE = GLFW_KEY_DELETE,
    RIGHT = GLFW_KEY_RIGHT,
    LEFT = GLFW_KEY_LEFT,
    DOWN = GLFW_KEY_DOWN,
    UP = GLFW_KEY_UP,
    F1 = GLFW_KEY_F1,
    F2 = GLFW_KEY_F2,
    F3 = GLFW_KEY_F3,
    F4 = GLFW_KEY_F4,
    F5 = GLFW_KEY_F5,
    F6 = GLFW_KEY_F6,
    F7 = GLFW_KEY_F7,
    F8 = GLFW_KEY_F8,
    F9 = GLFW_KEY_F9,
    F10 = GLFW_KEY_F10,
    F11 = GLFW_KEY_F11,
    F12 = GLFW_KEY_F12,
};

enum key_Actions
{
    PRESED = GLFW_PRESS,
    REPEATED = GLFW_REPEAT,
    RELEASED = GLFW_RELEASE,
};


